#!/usr/bin/env php
<?php

/**
 *. Consumer
 *.
 *. Simple consumer script that will connect directly to Kafka broker,
 *. and retrieve the messages since a given offset.
 *.
 *. Usage: ./scripts/simple/consumer -b {broker} -t {topic} [-o {offset}]
 *.
 *.     -b  Broker, the Kafka broker where we want to connect
 *.     -t  Topic, sets the topic where you want to produce
 *.     -o  Offset (optional), sets the starting point where
 *.         we want to consume
 *.     -h  Help, will display the help for the script
 *
 * @author      Michal Haris <michal.harish@gmail.com>
 * @date        2013-01-24
 */

// check script parametrs
$options = getopt("hb:t:o:");

// require kafka-php library
require __DIR__ . "/../../src/Kafka/Kafka.php";
require __DIR__ . "/../help.php";

if (!isset($options["b"])
    || !isset($options["t"])) {
    help();
}

$partition = 0;
$offset    = NULL;
$broker    = $options["b"];
$topic     = $options["t"];

if (isset($options["o"])) {
    $offset = new \Kafka\Offset($options["o"]);
}

list($host,$port) = explode(":", $broker);

// connection
$kafka = new \Kafka\Kafka($host, $port);

// consumer
$consumer = $kafka->createConsumer();

// offsets request
while (true) {
	try {
        $offsets = $consumer->offsets(
            $topic,
            $partition,
            \Kafka\Kafka::OFFSETS_EARLIEST
        );
		break;
	} catch (\Kafka\Exception $e) {
        echo "\nFailed to read offsets from partition $topic:$partition "
            . $e->getMessage();

		if (--$partition < 0) break;
	}
}

if ($offset === NULL || $offset < $offsets[0]) {
    $offset = $offsets[0];
    echo "Offset request earliest: '$topic:$partition' = $offset\n";
} else {
    echo "Reading from offset: '$topic:$partition' = $offset\n";
}

// initialize watermark offset
$watermark = clone $offset;

// fetch request
$totalProcessed = 0;

echo "\nFetch request from watermark offset: $watermark\n";

while ($consumer->fetch($topic, 0, $watermark)) {
    try {
        while ($message = $consumer->nextMessage()) {
            $consistent = TRUE;
            $processed = FALSE;

            do {
                try {
                    // no state has been modified yet, but there can be errors
                    // when fetching etc.
                    if (rand(0, 100) == 0) {
                        throw new Exception(
                            'Simulation of consumer failure in a consistent '
                            . 'state.'
                        );
                    }

                    // start processing the message ...
                    $consistent = FALSE;

                    if (rand(0, 200) == 0) {
                        throw new Exception(
                            'Simulation of consumer failure - THE ERROR '
                            . 'OCCURED WHILE THERE IS AN INCONSISTENT STATE '
                            . 'CREATED BY PARTIALLY PROCESSED MESSAGE!'
                        );
                    }

                    // if processing went fine, we get the new new watermark,
                    // but it's not over yet
                    $watermark = $consumer->getWatermark();

                    /*
                     * Now store the watermark somerwhere ...
                     *
                     * Only when the new watermark has been stored, we're
                     * consistent again and we can consider the last
                     * message 'processed'.
                     */
                    $consistent = TRUE;
                    $processed = TRUE;
                    $payload = $message->payload();

                    echo "\n[offset:" . $message->offset() . " watermark: $watermark]" . $message->payload() ;
                } catch (Exception $e) {
                    echo "\nError processing message at offset "
                        . "$watermark: " . $e->getMessage();
                    if (!$consistent) {
                        // compensate for the inconsistency, e.g. by
                        // reversing what was modified
                        $consistent = TRUE;
                    }
                    echo "\n";
                }
            } while (!$processed);

            $totalProcessed++;
        }
   } catch (Exception $e) {
       echo "\n\nError fetching message at offset $watermark: "
           . $e->getMessage();
       echo $e->getTraceAsString();
       break;
   }
}
echo "\nNo more messages. Total processed messages: $totalProcessed, "
    . "New watermark: " . $watermark . "\n\n";

// close the kafka consumer
$consumer->close();
