#!/usr/bin/env php
<?php

/**
 * Advanced producer with cached connector for heavy-weight php producers.
 * 
 *
 *
 * @author      Michal Harish <michal.harish@gmail.com>
 * @date        2012-12-03
 */
$t = microtime(true);

// bootstrap
require dirname(__FILE__) . "/../src/Kafka/Kafka.php";

$usage = "\nUsage: advanced-producer <zk.connect> <topicname> \"<message1>\" [\"<message2>\" [...]]";
if (count($argv) <= 1)  {
    exit($usage . "\n\n");
}

//create cached connector (default ttl is 1 minute)
$connector = $argv[1];
$pc = \Kafka\ProducerConnector::CreateCached($connector);

// get the topic from the second argument
if (count($argv) == 2)  {
    exit("{$usage}\nAvailable topics:\n\n" . implode("\n", $pc->getAvailableTopics()) . "\n\n");
}
$topic = $argv[2];

// add the messages (randomly distrubuted to the different broker/partitions) and produce
if (count($argv) == 3)  {
    exit("{$usage}\n\n");
}
for($i=3; $i<count($argv); $i++) {
    $payload = $argv[$i];
    $pc->addMessage($topic, $payload);
}
try {
    $pc->produce();
    echo "Produced ". ($i-3 ). " messages in ". (microtime(true) - $t) . " sedonds\n";
} catch (\Kafka\Exception $e) {
    /* What should happen here is to unlink the $cacheFile because 
     * the failure may have been due to one of the brokers going down,
     * and connector needs to be recreated to discover the new topology.
     */
}
