#!/usr/bin/env php
<?php

/**
 * Advanced consumer
 *
 * Script that will demonstrate a nice way to consume events from Kafka.
 *
 * @author      Pau Gay <pau.gay@visualdna.com>
 * @date        2012-11-14
 */

// bootstrap
require dirname(__FILE__) . "/../src/Kafka.php";

$topic = $argv[1];
$connector = $argv[2];

// $cc = new Kafka_ConsumerConnector("bl-queue-s01:2181");
$cc = new Kafka_ConsumerConnector($connector);
$messageStreams = $cc->createMessageStreams($topic, 65535 * 10);

$counter = 0;

while (true) {
    $fetchCount = 0;

    foreach ($messageStreams as $mid => $messageStream) {
        while ($message = $messageStream->nextMessage()) {
            $counter++;
            $fetchCount ++;
            echo str_repeat(chr(8), 10);
            echo str_pad($mid . ' ' . $counter, 10, ' ');
        }
        echo "\n";
    }

    if ($fetchCount == 0) {
        sleep(1);
        exit();
    }
}

echo "Counter = $counter\n";
