#!/usr/bin/env php
<?php

// bootstrap
require dirname(__FILE__) . "/../src/Kafka/Kafka.php";

// get arguments and defaults
$usage = "\nUsage: console-producer <topicname> [<zk.connect>]";
if (!isset($argv[1])) exit("$usage\n\n");
$topic = $argv[1];
$connectionString = isset($argv[2]) ? $argv[2] : 'localhost:2181';

$producerConnector = \Kafka\ProducerConnector::Create($connectionString);

//connection to the standard input
$stdin = fopen('php://stdin', 'r');
while ($line = trim(fgets($stdin)))
{
    $producerConnector->addMessage($topic, $line);
    $producerConnector->produce();
}