#!/usr/bin/env php
<?php

/**
 * Consumer
 *
 *. Script that demonstrates how to consume messages from a particular
 *. Kafka topic.
 *
 * @author      Pau Gay <pau.gay@visualdna.com>
 * @date        2013-01-23
 */

// require kafka-php library
require __DIR__ . "/../../src/Kafka/Kafka.php";
require __DIR__ . "/../help.php";

// check script parametrs
$options = getopt("c:t:");

if (!isset($options["c"])
    || !isset($options["t"])) {
    help();
}

$connector = $argv[1];
$topic = $argv[2];

// create the connector
$cc = new \Kafka\ConsumerConnector($connector);

// create the message stream
$messageStreams = $cc->createMessageStreams($topic, 65535 * 10);

$counter = 0;

while (true) {
    $fetchCount = 0;

    foreach ($messageStreams as $mid => $messageStream) {
        while ($message = $messageStream->nextMessage()) {
            $counter++;
            $fetchCount ++;
            echo str_repeat(chr(8), 10);
            echo str_pad($mid . ' ' . $counter, 10, ' ');
        }
        echo "\n";
    }

    if ($fetchCount == 0) {
        sleep(1);
        exit();
    }
}

echo "Counter = $counter\n";
