#!/usr/bin/env php
<?php

/**
 *. Daemon
 *.
 *. Daemon consumer that uses high-level consumer connector and continuously
 *. polls for new messages with hard-coded back-off interval 1 second.
 *. Use CTRL+C to finalise the daemon.
 *.
 *. Usage: ./scripts/consumer/daemon -c {connector} -t {topic}
 *.            [-o {output-format}] [-n {num-events}]
 *.
 *.     -c      Connector, set which Zookeeper server you want to connect
 *.     -t      Topic, sets the topic where you want to produce
 *.     -h      Help, will display the help for the script
 *.     -o      Output format, select between: json, php
 *.     -n      Number, show only N events
 *
 * @author      Pau Gay <pau.gay@visualdna.com>
 * @date        2013-01-24
 */

// check script parametrs
$options = getopt("hc:t:lo:n:");

// require kafka-php library
require __DIR__ . "/../../src/Kafka/Kafka.php";
require __DIR__ . "/../help.php";

if (!isset($options["c"])
    || !isset($options["t"])) {
    help();
}

$connector = $options["c"];
$topicFilter = new \Kafka\Whitelist($options["t"]);

// initialize connections
$consumerConnector = \Kafka\ConsumerConnector::Create($connector, "php-console-" . gethostname());
$messageStreams = $consumerConnector->createMessageStreamsByFilter(
    $topicFilter,
    65535
);

$count = 0;
while (true) {
    $fetchCount = 0;

    foreach ($messageStreams as $mid => $messageStream) {
        // keep getting messages, if we have more
        while ($message = $messageStream->nextMessage()) {
            $fetchCount++;
            $count++;

            if (isset($options["o"])
                && $options["o"] === "json") {
                echo $message->payload() . "\n";
            } else if (isset($options["o"])
                && $options["o"] === "php") {
                $data = json_decode($message->payload(), TRUE);
                var_export($data);
                echo "\n";
            } else {
                // just print topic and payload
                echo "{$count}. TOPIC=".$message->topic(). " PAYLOAD=";
                var_dump($message->payload());
            }

            if (isset($options["n"]) && $count >= $options["n"]) {
                exit(0);
            }
        }
    }

    if ($fetchCount == 0) {
        // no more messages, so sleep and try again
        sleep(1);
    }
}
