#!/usr/bin/env php
<?php

/**
 * Advanced producer
 *
 * Script that will demonstrate a nice way to produce events from Kafka.
 *
 * @author      Pau Gay <pau.gay@visualdna.com>
 * @date        2012-11-15
 */

// bootstrap
require __DIR__ . "/../../src/Kafka/Kafka.php";

$usage = "\nUsage: advanced-producer <zk.connect> <topicname> \"<message1>\" [\"<message2>\" [...]]";
if (count($argv) <= 1)  {
    exit($usage . "\n\n");
}

// create the producer
$connector = $argv[1];
$pc = \Kafka\ProducerConnector::Create($connector);

// get the topic from the second argument
if (count($argv) == 2)  {
    exit("{$usage}\nAvailable topics:\n\n" . implode("\n", $pc->getAvailableTopics()) . "\n\n");
}
$topic = $argv[2];

// add the messages (randomly distrubuted to the different broker/partitions)
if (count($argv) == 3)  {
    exit("{$usage}\n\n");
}

for($i=3; $i<count($argv); $i++) {
    $payload = $argv[$i];
    $pc->addMessage($topic, $payload);
}

// produce the actual messages into kafka
$pc->produce();
