#!/usr/bin/env php
<?php

/**
 * Advanced producer with custom MD5 partitioner applied on the payload
 *
 * Script that will demonstrate a nice way to produce events from Kafka.
 *
 * @author      Michal Haris <michal.haris@imagini.net>
 * @date        2012-11-15
 */

// bootstrap
require __DIR__ . "/../../src/Kafka/Kafka.php";

$usage = "\nUsage: advanced-producer-partitioner <zk.connect> <topicname> \"<payload>\"";

// default help
if (count($argv) <= 1)  {
    exit($usage . "\n\n");
}


// create the producer connector from the first argument with uuid partitioner
$connector = $argv[1];
class Md5Partitioner extends \Kafka\Partitioner {
    public function partition($md5Hash, $numPartitions) {
        return crc32($md5Hash) % $numPartitions;
    }
}
$producer = \Kafka\ProducerConnector::Create(
    $connector,
    \Kafka\Kafka::COMPRESSION_NONE,
    new Md5Partitioner()
);

// get the topic from the second argument
if (count($argv) == 2)  {
    exit("{$usage}\nAvailable topics:\n\n" . implode("\n", $producer->getAvailableTopics()) . "\n\n");
}
$topic = $argv[2];

// get the topic from the second argument
if (count($argv) == 3)  {
    exit($usage . "\n\n");
}

// get the payload from the third argument
$payload = $argv[3];

// add the messages distributed by the md5 of the payload
$producer->addMessage($topic, $payload, md5($payload));

// produce the actual messages into kafka
$producer->produce();
