#!/usr/bin/env php
<?php

/**
 *. Cached
 *.
 *. Producer with cached connector for heavy-weight php producers.
 *.
 *. Usage: ./scripts/producers/cached -c {connector} -t {topic} -m {message}
 *.        ./scripts/producers/cached -c {connector} -l
 *.
 *.     -c  Connector, set which Zookeeper server you want to connect
 *.     -t  Topic, sets the topic where you want to produce
 *.     -m  Message, sets the message you want to produce
 *.     -l  List, will list the available topics
 *.     -h  Help, will display the help for the script
 *
 * @author      Michal Harish <michal.harish@gmail.com>
 * @date        2012-12-03
 */

// check script parametrs
$options = getopt("hc:t:m:l");

// require kafka-php library
require __DIR__ . "/../../src/Kafka/Kafka.php";
require __DIR__ . "/../help.php";

if (!isset($options["c"])) {
    help();
}

$connector = $options["c"];
$producerCached = \Kafka\ProducerConnector::CreateCached($connector);

if (isset($options["l"]) && $options["l"] === false) {
    echo "\nAvailable topics:\n\n - "
        . implode("\n - ", $producerCached->getAvailableTopics())
        . "\n\n";
    exit(1);
}

if (!isset($options["t"])
    || !isset($options["m"])) {
    help();
}

$topic     = $options["t"];
$message   = $options["m"];

// add the message
$producerCached->addMessage($topic, $message);

try {
    // produce the actual messages into kafka
    $producerCached->produce();
} catch (\Kafka\Exception $e) {
    /*
     * What should happen here is to unlink the $cacheFile because
     * the failure may have been due to one of the brokers going down,
     * and connector needs to be recreated to discover the new topology.
     */
}
