#!/usr/bin/env php
<?php

/**
 *. Partitioned
 *.
 *. Advanced producer with custom MD5 partitioner applied on the payload.
 *.
 *. Usage: ./scripts/producers/partitioned -c {connector} -t {topic} -m {message}
 *.        ./scripts/producers/partitioned -c {connector} -l
 *.
 *.     -c  Connector, set which Zookeeper server you want to connect
 *.     -t  Topic, sets the topic where you want to produce
 *.     -m  Message, sets the message you want to produce
 *.     -l  List, will list the available topics
 *.     -h  Help, will display the help for the script
 *
 * @author      Michal Haris <michal.haris@imagini.net>
 * @date        2012-11-15
 */

// check script parametrs
$options = getopt("hc:t:m:l");

// require kafka-php library
require __DIR__ . "/../../src/Kafka/Kafka.php";
require __DIR__ . "/../help.php";

if (!isset($options["c"])) {
    help();
}

$connector = $options["c"];

// create the producer connector from the first argument with uuid partitioner
class Md5Partitioner extends \Kafka\Partitioner {
    public function partition($md5Hash, $numPartitions) {
        return crc32($md5Hash) % $numPartitions;
    }
}

$producer = \Kafka\ProducerConnector::Create(
    $connector,
    \Kafka\Kafka::COMPRESSION_NONE,
    new Md5Partitioner()
);

if (isset($options["l"]) && $options["l"] === false) {
    echo "\nAvailable topics:\n\n - "
        . implode("\n - ", $producer->getAvailableTopics())
        . "\n\n";
    exit(1);
}

if (!isset($options["t"])
    || !isset($options["m"])) {
    help();
}

$topic     = $options["t"];
$message   = $options["m"];

// add the messages distributed by the md5 of the payload
$producer->addMessage($topic, $message, md5($message));

// produce the actual messages into kafka
$producer->produce();
